# Run benchmarks on a remote system for the nightly (edge) build
# - Calls the reusable worflow remote-benchmarks.yml

name: Nightly Benchmark Test on Docker Deephaven

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  process-nightly-benchmarks:
    if: ${{github.repository_owner == 'deephaven'}}
    uses: ./.github/workflows/remote-benchmarks.yml
    with:
      run_type: nightly
      docker_image: "edge"
      run_label: ""
      test_package: "io.deephaven.benchmark.tests.standard"
      test_class_regex: "^(Test.*|.+[.$]Test.*|.*Tests?)$"
      scale_row_count: 10000000
    secrets: inherit
